language: cpp
compiler:
  - g++
  - clang++
os:
  - linux
  - osx
osx_image: xcode61
env:
  - COMPILE_FLAGS=-lpthread -Wno-switch
script: $CXX src/*.cpp -o icetea $COMPILE_FLAGS
test: $CXX src/*.cpp main.cpp -o icetea $COMPILE_FLAGS && ./icetea -o tests/run_tests.os
