.TH "src Directory Reference" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcli\&.h\fP"
.br
.RI "\fIA header-only command line argument parsing library\&. \fP"
.ti -1c
.RI "file \fBfast_mutex\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "\fIThe main \fBIceTea\fP logic\&. \fP"
.ti -1c
.RI "file \fBos\-std\&.cpp\fP"
.br
.RI "\fIObjectScript standart library extension\&. \fP"
.ti -1c
.RI "file \fBthreading\&.h\fP"
.br
.RI "\fIA Threadpool based on Tinythreads++\&. \fP"
.ti -1c
.RI "file \fBtinythread\&.h\fP"
.br
.in -1c
