.TH "AsyncProcess" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsyncProcess \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstlplus::async_subprocess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetStdout\fP ()"
.br
.ti -1c
.RI "std::string \fBgetStderr\fP ()"
.br
.ti -1c
.RI "bool \fBcallback\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 29 of file os\-exec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
