.TH "src/cli.h" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cli.h \- A header-only command line argument parsing library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCLI\fP"
.br
.RI "\fICommand Line Interface class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A header-only command line argument parsing library\&. 

This small header contains only one class: \fBCLI\fP
.PP
This class can handle command line options - long and short - as well as setting and retriving default values\&. 
.PP
Definition in file \fBcli\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
