.TH "CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputWriter" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputWriter \- interface definition for the \fBOutputWriter\fP object to pass to \fBSave()\fP in order to output the INI file data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleIni\&.h>\fP
.PP
Inherited by \fBCSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::FileWriter\fP, and \fBCSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::StringWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBWrite\fP (const char *a_pBuf)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SI_CHAR, class SI_STRLESS, class SI_CONVERTER>
.br
class CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::OutputWriter"
interface definition for the \fBOutputWriter\fP object to pass to \fBSave()\fP in order to output the INI file data\&. 
.PP
Definition at line 363 of file SimpleIni\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
