.TH "CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter \- Characterset conversion utility class to convert strings to the same format as is used for the storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleIni\&.h>\fP
.PP
Inherits SI_CONVERTER\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConverter\fP (bool a_bStoreIsUtf8)"
.br
.ti -1c
.RI "\fBConverter\fP (const \fBConverter\fP &rhs)"
.br
.ti -1c
.RI "\fBConverter\fP & \fBoperator=\fP (const \fBConverter\fP &rhs)"
.br
.ti -1c
.RI "bool \fBConvertToStore\fP (const SI_CHAR *a_pszString)"
.br
.ti -1c
.RI "const char * \fBData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SI_CHAR, class SI_STRLESS, class SI_CONVERTER>
.br
class CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter"
Characterset conversion utility class to convert strings to the same format as is used for the storage\&. 
.PP
Definition at line 417 of file SimpleIni\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
