.TH "src/fast_mutex.h" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fast_mutex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtthread::fast_mutex\fP"
.br
.RI "\fIFast mutex class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtthread\fP"
.br
.RI "\fIMain name space for TinyThread++\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
