.TH "FloatFormatStr< long double >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FloatFormatStr< long double > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBroundFmt\fP ()"
.br
.ti -1c
.RI "static const char * \fBprecisionFmt\fP ()"
.br
.ti -1c
.RI "static const char * \fBautoFmt\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct FloatFormatStr< long double >"

.PP
Definition at line 724 of file objectscript\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
