.TH "IceTeaPlugin" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaPlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBIceTeaCache\fP, \fBIceTeaConsole\fP, \fBIceTeaDetector\fP, \fBIceTeaGeneral\fP, \fBIceTeaPFS\fP, \fBIceTeaProcess\fP, \fBIceTeaSLRE\fP, \fBIceTeaSTD\fP, \fBIceTeaSubProcess\fP, and \fBIceTeaSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBconfigure\fP (\fBIceTea\fP *)=0"
.br
.ti -1c
.RI "virtual std::string \fBgetName\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBgetDescription\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file IceTeaPlugin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
