.TH "IceTeaSLRE" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaSLRE \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIceTeaPlugin\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 52 of file os\-slre\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
