.TH "IceTeaGeneralInternalPlugin" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaGeneralInternalPlugin \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIceTeaGeneralProvider\fP * \fBgetProvider\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 206 of file os\-icetea\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
