.TH "IceTeaSystemInternalPlugin" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaSystemInternalPlugin \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIceTeaSystemProvider\fP * \fBgetProvider\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file os\-sys\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
