.TH "IceTeaDetectorInternalPlugin" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaDetectorInternalPlugin \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIceTeaDetectorProvider\fP * \fBgetProvider\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file os\-detector\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
