.TH "IceTeaPFS" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaPFS \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIceTeaPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBconfigure\fP (\fBIceTea\fP *os)"
.br
.ti -1c
.RI "string \fBgetName\fP ()"
.br
.ti -1c
.RI "string \fBgetDescription\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file os\-pfs\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
