.TH "IceTeaPluginProvider" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaPluginProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpluma::Provider\fP\&.
.PP
Inherited by \fBIceTeaCacheProvider\fP, \fBIceTeaConsoleProvider\fP, \fBIceTeaDetectorProvider\fP, \fBIceTeaGeneralProvider\fP, \fBIceTeaPFSProvider\fP, \fBIceTeaProcessProvider\fP, \fBIceTeaSLREProvider\fP, \fBIceTeaSTDProvider\fP, \fBIceTeaSubProcessProvider\fP, and \fBIceTeaSystemProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBgetVersion\fP () const "
.br
.RI "\fIGet provider version\&. \fP"
.ti -1c
.RI "virtual \fBIceTeaPlugin\fP * \fBcreate\fP () const  =0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBpluma::Pluma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file IceTeaPlugin\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int IceTeaPluginProvider::getVersion () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get provider version\&. 
.PP
\fBReturns:\fP
.RS 4
Version number\&. 
.RE
.PP

.PP
Implements \fBpluma::Provider\fP\&.
.PP
Definition at line 21 of file IceTeaPlugin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
