.TH "IceTeaConsoleProvider" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IceTeaConsoleProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIceTeaPluginProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIceTeaPlugin\fP * \fBcreate\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 275 of file os\-console\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
