.TH "InternalPluginStore" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InternalPluginStore \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBattach\fP (\fBIceTeaPluginProvider\fP *)"
.br
.ti -1c
.RI "static IceTeaInternalPlugins * \fBgetStore\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file InternalIceTeaPlugin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
