.TH "src/main.cpp" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- The main \fBIceTea\fP logic\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'IceTea\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main \fBIceTea\fP logic\&. 

This file contains and holds upon all the functions that translate targets, actions, externals and rules into some logic\&. This is done by processing the input using a single thread, and executing the tasks over a multiple of threads (depending on the given hardware)\&.
.PP
Only minor additions are made to the script environment, that contain simple wrapper functions\&. 
.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
