.TH "memorymanager" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memorymanager \- Memory management 

.SH "Overview"
.PP
Efficient memory manager\&.
.SH "Symbols for configuring memory manager"
.PP
.PD 0
.IP "\(bu" 2
\fCOS_HEAP_CHUNK_SIZE\fP defines size of chunk where each of objects with size <= OS_HEAP_CHUNK_SIZE is stored\&. Value must be a power of two\&. Maximum recommended value is 256\&. Defaults are 128 or 256 depending on memory allocation strategy (see OS_USE_HEAP_SAVING_MODE)\&.
.PP
.PD 0
.IP "\(bu" 2
\fCOS_HEAP_PAGE_SIZE\fP is used to define size of page where medium sized objects are stored\&. Value must be a power of two\&. Maximum recommended value is 65536\&. After exhausting existing page, new one with size OS_HEAP_PAGE_SIZE is allocated from system\&. Default value is 32 kbytes\&.
.PP
.PD 0
.IP "\(bu" 2
\fCOS_DEBUG\fP enables debugging mode in allocator\&. It uses more memory, but enables memory overrun and heap corruption detection\&.
.PP
.PD 0
.IP "\(bu" 2
\fCOS_USE_HEAP_SAVING_MODE\fP enables heap-saving mode where pages are not used\&. But enabling this results in performance drop\&.
.PP
.PD 0
.IP "\(bu" 2
\fCDEBUG_APP_HEAP_DUMP_LEAK_ON_EXIT\fP enables creation of log-file named 'dump-err-exit\&.log' on application exit\&. File contains information about memory leaks\&. 
.PP

