.TH "ObjectScript::CtypeValue< long >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::CtypeValue< long > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::CtypeNumber< long >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::CtypeValue< long >"

.PP
Definition at line 231 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
