.TH "ObjectScript::OS::Core::Strings" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Strings \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStrings\fP (\fBOS\fP *allocator)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fB__construct\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__destruct\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__instantiable\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__newinstance\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__callinstance\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__object\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__get\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__set\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__isset\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__getAt\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__setAt\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__issetAt\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__del\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__delAt\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__getempty\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__setempty\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__delempty\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__getdim\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__setdim\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__deldim\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__iter\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__cmp\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__bitand\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__bitor\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__bitxor\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__bitnot\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__plus\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__minus\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__len\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__add\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__sub\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__mul\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__div\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__mod\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__lshift\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rshift\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__pow\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rcmp\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rbitand\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rbitor\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rbitxor\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__radd\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rsub\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rmul\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rdiv\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rmod\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rlshift\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rrshift\fP"
.br
.ti -1c
.RI "\fBString\fP \fB__rpow\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_unhandledException\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_getFilename\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_getDirname\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_extends\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_delete\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_length\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_in\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_is\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_as\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_push\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_valueOf\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_clone\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_concat\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_echo\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_require\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_call\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_core\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_main\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfunc_defineConstProperty\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_null\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_boolean\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_number\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_string\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_object\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_array\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_userdata\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtypeof_function\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_get\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_set\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_super\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_is\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_as\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_extends\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_delete\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_prototype\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_var\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_local\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_arguments\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_function\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_null\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_true\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_false\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_return\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_class\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_enum\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_switch\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_case\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_default\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_if\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_else\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_elseif\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_for\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_in\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_break\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_continue\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_try\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_catch\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_finally\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_throw\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_new\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_while\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_do\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_const\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_public\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_protected\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_private\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_yield\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_static\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_debugger\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_debuglocals\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_line\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_file\fP"
.br
.ti -1c
.RI "\fBString\fP \fBsyntax_dir\fP"
.br
.ti -1c
.RI "\fBString\fP \fBvar_globals\fP"
.br
.ti -1c
.RI "\fBString\fP \fBvar_func\fP"
.br
.ti -1c
.RI "\fBString\fP \fBvar_this\fP"
.br
.ti -1c
.RI "\fBString\fP \fBvar_env\fP"
.br
.ti -1c
.RI "\fBString\fP \fBvar_temp_prefix\fP"
.br
.ti -1c
.RI "\fBString\fP \fBempty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2428 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
