.TH "ObjectScript::OS::Core::Compiler::ExpressionList" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Compiler::ExpressionList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Vector< Expression * >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpressionList\fP (\fBOS\fP *)"
.br
.ti -1c
.RI "bool \fBisValue\fP () const "
.br
.ti -1c
.RI "bool \fBisClear\fP () const "
.br
.ti -1c
.RI "bool \fBisWriteable\fP () const "
.br
.ti -1c
.RI "\fBExpression\fP * \fBadd\fP (\fBExpression\fP *)"
.br
.ti -1c
.RI "\fBExpression\fP * \fBinsert\fP (int i, \fBExpression\fP *)"
.br
.ti -1c
.RI "\fBExpression\fP * \fBremoveIndex\fP (int i)"
.br
.ti -1c
.RI "\fBExpression\fP * \fBremoveLast\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fBExpressionList\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOS\fP * \fBallocator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1788 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
