.TH "ObjectScript::OS::Utils" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Utils \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBENumberParseType\fP { \fBPARSE_TOKEN\fP, \fBPARSE_INT\fP, \fBPARSE_FLOAT\fP }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBparseFloat\fP (const char *&str, \fBFloatType\fP< double >::type &val, ENumberParseType parse_type, int int_radix=10)"
.br
.ti -1c
.RI "static char * \fBnumToStr\fP (char *, __int32 value)"
.br
.ti -1c
.RI "static char * \fBnumToStr\fP (char *, __int64 value)"
.br
.ti -1c
.RI "static char * \fBnumToStr\fP (char *, \fBFloatType\fP< double >::type value)"
.br
.ti -1c
.RI "static char * \fBnumToStr\fP (char *, \fBFloatType\fP< double >::type value, int precision)"
.br
.ti -1c
.RI "static __int64 \fBstrToInt\fP (const char *)"
.br
.ti -1c
.RI "static \fBFloatType\fP< double >::type \fBstrToFloat\fP (const char *)"
.br
.ti -1c
.RI "static int \fBkeyToHash\fP (const void *, int size)"
.br
.ti -1c
.RI "static int \fBkeyToHash\fP (const void *buf1, int size1, const void *buf2, int size2)"
.br
.ti -1c
.RI "static int \fBcmp\fP (const void *buf1, int len1, const void *buf2, int len2)"
.br
.ti -1c
.RI "static double \fBround\fP (double a, int precision=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 378 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
