.TH "ObjectScript::OS_FunctionImp0_run< R >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS_FunctionImp0_run< R > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef R(* \fBF\fP) ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBrun\fP (\fBOS\fP *os, int params, int, int, void *user_param)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class R>
.br
struct ObjectScript::OS_FunctionImp0_run< R >"

.PP
Definition at line 1123 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
