.TH "ObjectScript::OS::Core::Compiler::Params" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Compiler::Params \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParams\fP (const \fBParams\fP &)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowRootBlocks\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowVarDecl\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowInlineNestedBlock\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowBinaryOperator\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowInOperator\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowAssign\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowParams\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowAutoCall\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowCall\fP (bool)"
.br
.ti -1c
.RI "\fBParams\fP & \fBsetAllowNopResult\fP (bool)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBallow_root_blocks\fP"
.br
.ti -1c
.RI "bool \fBallow_var_decl\fP"
.br
.ti -1c
.RI "bool \fBallow_inline_nested_block\fP"
.br
.ti -1c
.RI "bool \fBallow_binary_operator\fP"
.br
.ti -1c
.RI "bool \fBallow_in_operator\fP"
.br
.ti -1c
.RI "bool \fBallow_assing\fP"
.br
.ti -1c
.RI "bool \fBallow_params\fP"
.br
.ti -1c
.RI "bool \fBallow_auto_call\fP"
.br
.ti -1c
.RI "bool \fBallow_call\fP"
.br
.ti -1c
.RI "bool \fBallow_nop_result\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2091 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
