.TH "ObjectScript::FunctionDataChain" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::FunctionDataChain \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjectScript::FunctionData< F >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionDataChain\fP * \fBfind\fP ()"
.br
.ti -1c
.RI "void \fBregisterFunctionData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "int \fBdata_size\fP"
.br
.ti -1c
.RI "\fBFunctionDataChain\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 370 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
