.TH "ObjectScript::RemovePtr< T >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::RemovePtr< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct ObjectScript::RemovePtr< T >"

.PP
Definition at line 47 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
