.TH "ObjectScript::OS::Core::Table" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Table \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIteratorState\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProperty\fP * \fBget\fP (const \fBValue\fP &index, int index_type)"
.br
.ti -1c
.RI "bool \fBcontainsIterator\fP (\fBIteratorState\fP *)"
.br
.ti -1c
.RI "void \fBaddIterator\fP (\fBIteratorState\fP *)"
.br
.ti -1c
.RI "void \fBremoveIterator\fP (\fBIteratorState\fP *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProperty\fP ** \fBheads\fP"
.br
.ti -1c
.RI "int \fBhead_mask\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "__int64 \fBnext_index\fP"
.br
.ti -1c
.RI "\fBProperty\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBProperty\fP * \fBlast\fP"
.br
.ti -1c
.RI "\fBIteratorState\fP * \fBiterators\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1204 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
