.TH "ObjectScript::FunctionData< F >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::FunctionData< F > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::FunctionDataChain\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionData\fP (F _f)"
.br
.ti -1c
.RI "\fBFunctionData\fP (const \fBFunctionData\fP &_f)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionData\fP * \fBcreate\fP (F _f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "F \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class F>
.br
struct ObjectScript::FunctionData< F >"

.PP
Definition at line 384 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
