.TH "ObjectScript::OS::Core::Tokenizer::TextData" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Tokenizer::TextData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextData\fP (\fBOS\fP *)"
.br
.ti -1c
.RI "\fBTextData\fP * \fBretain\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOS\fP * \fBallocator\fP"
.br
.ti -1c
.RI "\fBString\fP \fBfilename\fP"
.br
.ti -1c
.RI "bool \fBis_real_file\fP"
.br
.ti -1c
.RI "\fBVector\fP< \fBString\fP > \fBlines\fP"
.br
.ti -1c
.RI "int \fBref_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1070 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
