.TH "ObjectScript::OS::Vector< T >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Vector< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int i) const "
.br
.ti -1c
.RI "T & \fBlastElement\fP ()"
.br
.ti -1c
.RI "const T & \fBlastElement\fP () const "
.br
.ti -1c
.RI "bool \fBcontains\fP (const T &val) const "
.br
.ti -1c
.RI "int \fBindexOf\fP (const T &val) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBcapacity\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct ObjectScript::OS::Vector< T >"

.PP
Definition at line 413 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
