.TH "ObjectScript::OS::Core::GCArrayValue" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::GCArrayValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::GCValue\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector\fP< \fBValue\fP > \fBvalues\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1484 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
