.TH "ObjectScript::CtypeName< ObjectScript::OS::String >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::CtypeName< ObjectScript::OS::String > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBgetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::CtypeName< ObjectScript::OS::String >"

.PP
Definition at line 131 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
