.TH "ObjectScript::OS::Core::FileStreamWriter" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::FileStreamWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::StreamWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileStreamWriter\fP (\fBOS\fP *, const char *filename)"
.br
.ti -1c
.RI "int \fBgetPos\fP () const "
.br
.ti -1c
.RI "void \fBsetPos\fP (int)"
.br
.ti -1c
.RI "int \fBgetSize\fP () const "
.br
.ti -1c
.RI "void \fBwriteBytes\fP (const void *, int len)"
.br
.ti -1c
.RI "void \fBwriteBytesAtPos\fP (const void *, int len, int pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFileHandle\fP * \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 692 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
