.TH "ObjectScript::OS::Core::Tokenizer::TokenData" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Tokenizer::TokenData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOS\fP * \fBgetAllocator\fP () const "
.br
.ti -1c
.RI "\fBFloatType\fP< double >::type \fBgetFloat\fP () const "
.br
.ti -1c
.RI "\fBTokenData\fP (\fBTextData\fP *text_data, const \fBString\fP &p_str, TokenType p_type, int p_line, int p_pos)"
.br
.ti -1c
.RI "\fBTokenData\fP * \fBretain\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBsetFloat\fP (\fBFloatType\fP< double >::type value)"
.br
.ti -1c
.RI "\fBoperator String\fP () const "
.br
.ti -1c
.RI "bool \fBisTypeOf\fP (TokenType tokenType) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTextData\fP * \fBtext_data\fP"
.br
.ti -1c
.RI "\fBString\fP \fBstr\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "int \fBref_count\fP"
.br
.ti -1c
.RI "TokenType \fBtype\fP"
.br
.ti -1c
.RI "\fBFloatType\fP< double >::type \fBfloat_value\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBFloatType\fP< double >::type \fBfloat_value\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1091 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
