.TH "ObjectScript::OS::Core::MemStreamWriter" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::MemStreamWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::StreamWriter\fP\&.
.PP
Inherited by \fBObjectScript::OS::Core::Buffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemStreamWriter\fP (\fBOS\fP *)"
.br
.ti -1c
.RI "int \fBgetPos\fP () const "
.br
.ti -1c
.RI "void \fBsetPos\fP (int)"
.br
.ti -1c
.RI "int \fBgetSize\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBreserveCapacity\fP (int new_capacity)"
.br
.ti -1c
.RI "void \fBwriteBytes\fP (const void *, int len)"
.br
.ti -1c
.RI "void \fBwriteBytesAtPos\fP (const void *, int len, int pos)"
.br
.ti -1c
.RI "void \fBwriteByte\fP (int)"
.br
.ti -1c
.RI "void \fBwriteByteAtPos\fP (int value, int pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVector\fP< unsigned char > \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 667 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
