.TH "ObjectScript::CtypeValue< bool >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::CtypeValue< bool > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef bool \fBtype\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisValid\fP (type)"
.br
.ti -1c
.RI "static type \fBdef\fP (\fBObjectScript::OS\fP *)"
.br
.ti -1c
.RI "static type \fBgetArg\fP (\fBObjectScript::OS\fP *os, int offs)"
.br
.ti -1c
.RI "static void \fBpush\fP (\fBObjectScript::OS\fP *os, bool val)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::CtypeValue< bool >"

.PP
Definition at line 88 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
