.TH "ObjectScript::OSHeapManager::FreeBlock" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OSHeapManager::FreeBlock \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OSHeapManager::Block\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBresetFreeLink\fP ()"
.br
.ti -1c
.RI "void \fBremoveFreeLink\fP ()"
.br
.ti -1c
.RI "void \fBinsertAfterFreeLink\fP (\fBFreeBlock\fP *block)"
.br
.ti -1c
.RI "void \fBinsertBeforeFreeLink\fP (\fBFreeBlock\fP *block)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFreeBlock\fP * \fBprev_free\fP"
.br
.ti -1c
.RI "\fBFreeBlock\fP * \fBnext_free\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 267 of file os\-heap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
