.TH "ObjectScript::OS::Core::Value" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Value \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBValid\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP (bool)"
.br
.ti -1c
.RI "\fBValue\fP (__int32)"
.br
.ti -1c
.RI "\fBValue\fP (__int64)"
.br
.ti -1c
.RI "\fBValue\fP (float)"
.br
.ti -1c
.RI "\fBValue\fP (double)"
.br
.ti -1c
.RI "\fBValue\fP (long double)"
.br
.ti -1c
.RI "\fBValue\fP (\fBGCValue\fP *)"
.br
.ti -1c
.RI "\fBValue\fP (\fBGCValue\fP *, const \fBValid\fP &)"
.br
.ti -1c
.RI "\fBValue\fP (const \fBString\fP &)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (\fBGCValue\fP *)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (bool)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (__int32)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (__int64)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (float)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (double)"
.br
.ti -1c
.RI "\fBValue\fP & \fBoperator=\fP (long double)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBGCValue\fP * \fBgetGCValue\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBValue\fP &b) const "
.br
.ti -1c
.RI "bool \fBisNull\fP () const "
.br
.ti -1c
.RI "bool \fBisFunction\fP () const "
.br
.ti -1c
.RI "bool \fBisUserdata\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBValueUnion\fP \fBv\fP"
.br
.ti -1c
.RI "   int \fBtype\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1386 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
