.TH "ObjectScript::UserDataDestructor< OS::Core::File >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::UserDataDestructor< OS::Core::File > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdtor\fP (\fBObjectScript::OS\fP *os, void *data, void *user_param)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::UserDataDestructor< OS::Core::File >"

.PP
Definition at line 25340 of file objectscript\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
