.TH "ObjectScript::OS::Core::Program::DebugInfoItem" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Program::DebugInfoItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugInfoItem\fP (int line, int pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned __int32 \fBline\fP"
.br
.ti -1c
.RI "unsigned __int32 \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2279 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
