.TH "ObjectScript::OS::Core::Compiler::Expression" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Compiler::Expression \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjectScript::OS::Core::Compiler::Scope\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpression\fP (ExpressionType type, \fBTokenData\fP *)"
.br
.ti -1c
.RI "\fBExpression\fP (ExpressionType type, \fBTokenData\fP *, \fBExpression\fP *e1)"
.br
.ti -1c
.RI "\fBExpression\fP (ExpressionType type, \fBTokenData\fP *, \fBExpression\fP *e1, \fBExpression\fP *e2)"
.br
.ti -1c
.RI "\fBExpression\fP (ExpressionType type, \fBTokenData\fP *, \fBExpression\fP *e1, \fBExpression\fP *e2, \fBExpression\fP *e3)"
.br
.ti -1c
.RI "\fBOS\fP * \fBgetAllocator\fP ()"
.br
.ti -1c
.RI "double \fBtoNumber\fP ()"
.br
.ti -1c
.RI "__int64 \fBtoInt\fP ()"
.br
.ti -1c
.RI "\fBString\fP \fBtoString\fP ()"
.br
.ti -1c
.RI "bool \fBisConstValue\fP () const "
.br
.ti -1c
.RI "bool \fBisValue\fP () const "
.br
.ti -1c
.RI "bool \fBisClear\fP () const "
.br
.ti -1c
.RI "bool \fBisWriteable\fP () const "
.br
.ti -1c
.RI "bool \fBisOperator\fP () const "
.br
.ti -1c
.RI "bool \fBisUnaryOperator\fP () const "
.br
.ti -1c
.RI "bool \fBisBinaryOperator\fP () const "
.br
.ti -1c
.RI "bool \fBisAssignOperator\fP () const "
.br
.ti -1c
.RI "bool \fBisLogicOperator\fP () const "
.br
.ti -1c
.RI "\fBString\fP \fBgetSlotStr\fP (\fBCompiler\fP *compiler, \fBScope\fP *scope, int slot_num, int up_count=0)"
.br
.ti -1c
.RI "void \fBdebugPrint\fP (\fBBuffer\fP &, \fBCompiler\fP *compiler, \fBScope\fP *scope, int depth)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisAssignOperator\fP (ExpressionType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTokenData\fP * \fBtoken\fP"
.br
.ti -1c
.RI "\fBExpressionList\fP \fBlist\fP"
.br
.ti -1c
.RI "\fBLocalVarDesc\fP \fBlocal_var\fP"
.br
.ti -1c
.RI "unsigned short \fBactive_locals\fP"
.br
.ti -1c
.RI "unsigned short \fBret_values\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   short \fBa\fP"
.br
.ti -1c
.RI "   short \fBb\fP"
.br
.ti -1c
.RI "   short \fBc\fP"
.br
.ti -1c
.RI "} \fBslots\fP"
.br
.ti -1c
.RI "ExpressionType \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1833 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
