.TH "ObjectScript::OS::Core::GCFunctionValue" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::GCFunctionValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::GCValue\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProgram\fP * \fBprog\fP"
.br
.ti -1c
.RI "\fBFunctionDecl\fP * \fBfunc_decl\fP"
.br
.ti -1c
.RI "\fBValue\fP \fBenv\fP"
.br
.ti -1c
.RI "\fBValue\fP \fBself\fP"
.br
.ti -1c
.RI "\fBLocals\fP * \fBlocals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1492 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
