.TH "ObjectScript::OS::Core::FileStreamReader" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::FileStreamReader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::StreamReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileStreamReader\fP (\fBOS\fP *, const char *filename)"
.br
.ti -1c
.RI "int \fBgetPos\fP () const "
.br
.ti -1c
.RI "void \fBsetPos\fP (int)"
.br
.ti -1c
.RI "int \fBgetSize\fP () const "
.br
.ti -1c
.RI "void \fBmovePos\fP (int len)"
.br
.ti -1c
.RI "bool \fBcheckBytes\fP (const void *, int len)"
.br
.ti -1c
.RI "void * \fBreadBytes\fP (void *, int len)"
.br
.ti -1c
.RI "void * \fBreadBytesAtPos\fP (void *, int len, int pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFileHandle\fP * \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 793 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
