.TH "ObjectScript::OS::Core::Values" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Values \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGCValue\fP * \fBget\fP (int value_id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGCValue\fP ** \fBheads\fP"
.br
.ti -1c
.RI "int \fBhead_mask\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBnext_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2412 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
