.TH "ObjectScript::OS::Core::Locals" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Locals \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocals\fP ** \fBgetParents\fP ()"
.br
.ti -1c
.RI "\fBLocals\fP * \fBgetParent\fP (int i)"
.br
.ti -1c
.RI "void \fBsetParent\fP (int i, \fBLocals\fP *)"
.br
.ti -1c
.RI "\fBLocals\fP * \fBretain\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBref_count\fP"
.br
.ti -1c
.RI "int \fBgc_step_type\fP"
.br
.ti -1c
.RI "\fBProgram\fP * \fBprog\fP"
.br
.ti -1c
.RI "\fBFunctionDecl\fP * \fBfunc_decl\fP"
.br
.ti -1c
.RI "\fBValue\fP * \fBvalues\fP"
.br
.ti -1c
.RI "bool \fBis_stack_locals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2320 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
