.TH "ObjectScript::OS::Core::Property" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Property \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProperty\fP (const \fBValue\fP &index, const \fBValue\fP &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBValue\fP \fBindex\fP"
.br
.ti -1c
.RI "\fBValue\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBProperty\fP * \fBhash_next\fP"
.br
.ti -1c
.RI "\fBProperty\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBProperty\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1508 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
