.TH "ObjectScript::CtypeValue< std::string >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::CtypeValue< std::string > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::string \fBtype\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisValid\fP (const type &)"
.br
.ti -1c
.RI "static type \fBdef\fP (\fBObjectScript::OS\fP *)"
.br
.ti -1c
.RI "static type \fBgetArg\fP (\fBObjectScript::OS\fP *os, int offs)"
.br
.ti -1c
.RI "static void \fBpush\fP (\fBObjectScript::OS\fP *os, const type &val)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::CtypeValue< std::string >"

.PP
Definition at line 111 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
