.TH "ObjectScript::OS::Core::GCUserdataValue" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::GCUserdataValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::GCObjectValue\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcrc\fP"
.br
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "OS_UserdataDtor \fBdtor\fP"
.br
.ti -1c
.RI "void * \fBuser_param\fP"
.br
.ti -1c
.RI "\fBGCUserdataValue\fP * \fBhash_next_ref\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1309 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
