.TH "ObjectScript::FloatType< double >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::FloatType< double > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef double \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::FloatType< double >"

.PP
Definition at line 230 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
