.TH "ObjectScript::OS::Core::Compiler::LocalVarDesc" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Compiler::LocalVarDesc \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBup_count\fP"
.br
.ti -1c
.RI "unsigned short \fBup_scope_count\fP"
.br
.ti -1c
.RI "unsigned short \fBindex\fP"
.br
.ti -1c
.RI "ELocalVarScopeType \fBscope_type\fP"
.br
.ti -1c
.RI "ECompiledValueType \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1821 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
