.TH "ObjectScript::CtypeValue< int >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::CtypeValue< int > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::CtypeNumber< int >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::CtypeValue< int >"

.PP
Definition at line 225 of file os\-binder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
