.TH "ObjectScript::OS::Core::Compiler::Scope::LocalVar" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Compiler::Scope::LocalVar \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalVar\fP (const \fBString\fP &name, int index, ECompiledValueType type=CVT_UNKNOWN)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBname\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "ECompiledValueType \fBtype\fP"
.br
.ti -1c
.RI "bool \fBupvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1877 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
