.TH "ObjectScript::OS::Core::Buffer" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::Buffer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Core::MemStreamWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuffer\fP (\fBOS\fP *)"
.br
.ti -1c
.RI "\fBBuffer\fP (const \fBBuffer\fP &)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBappend\fP (char)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBappend\fP (const char *)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBappend\fP (const char *, int len)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBappend\fP (const void *, int size)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBappend\fP (const \fBCore::String\fP &)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBappend\fP (const \fBBuffer\fP &)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBoperator+=\fP (const \fBCore::String\fP &)"
.br
.ti -1c
.RI "\fBBuffer\fP & \fBoperator+=\fP (const char *)"
.br
.ti -1c
.RI "\fBoperator Core::String\fP ()"
.br
.ti -1c
.RI "\fBCore::String\fP \fBtoString\fP ()"
.br
.ti -1c
.RI "\fBOS::String\fP \fBtoStringOS\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBCore::GCStringValue\fP * \fBtoGCStringValue\fP ()"
.br
.ti -1c
.RI "void \fBfreeCacheStr\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fBBuffer\fP &)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCore::GCStringValue\fP * \fBcache_str\fP"
.br
.ti -1c
.RI "\fBOS\fP * \fBallocator\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 893 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
