.TH "ObjectScript::CtypeValue< OS::Core::File * >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::CtypeValue< OS::Core::File * > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::CtypeUserClass< OS::CoreFile * >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ObjectScript::CtypeValue< OS::Core::File * >"

.PP
Definition at line 25339 of file objectscript\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
