.TH "ObjectScript::OS::Core::FunctionDecl" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::FunctionDecl \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLocalVar\fP"
.br
.ti -1c
.RI "struct \fBTryBlock\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBprog_parent_func_index\fP"
.br
.ti -1c
.RI "\fBLocalVar\fP * \fBlocals\fP"
.br
.ti -1c
.RI "int \fBstack_size\fP"
.br
.ti -1c
.RI "int \fBnum_locals\fP"
.br
.ti -1c
.RI "int \fBnum_params\fP"
.br
.ti -1c
.RI "int \fBmax_up_count\fP"
.br
.ti -1c
.RI "int \fBfunc_depth\fP"
.br
.ti -1c
.RI "int \fBfunc_index\fP"
.br
.ti -1c
.RI "int \fBnum_local_funcs\fP"
.br
.ti -1c
.RI "\fBTryBlock\fP * \fBtry_blocks\fP"
.br
.ti -1c
.RI "int \fBnum_try_blocks\fP"
.br
.ti -1c
.RI "int \fBopcodes_pos\fP"
.br
.ti -1c
.RI "int \fBopcodes_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2215 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
