.TH "ObjectScript::OS::Core::FunctionDecl::TryBlock" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::FunctionDecl::TryBlock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstart_code_pos\fP"
.br
.ti -1c
.RI "int \fBend_code_pos\fP"
.br
.ti -1c
.RI "int \fBcatch_var_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2228 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
