.TH "ObjectScript::OS::Core::StackValues" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::StackValues \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "\fBValue\fP & \fBlastElement\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBValue\fP * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBcapacity\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2600 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
