.TH "ObjectScript::OSHeapManager::Stats" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OSHeapManager::Stats \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OSHeapManager::SimpleStats\fP\&.
.PP
Inherited by \fBObjectScript::OSHeapManager::SummaryStats\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned __int32 \fBmerge_count\fP"
.br
.ti -1c
.RI "unsigned __int32 \fBfree_page_count\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 151 of file os\-heap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
