.TH "ObjectScript::OS::Core::ValueUnion" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::ValueUnion \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBboolean\fP"
.br
.ti -1c
.RI "\fBGCValue\fP * \fBvalue\fP"
.br
.ti -1c
.RI "\fBGCObjectValue\fP * \fBobject\fP"
.br
.ti -1c
.RI "\fBGCArrayValue\fP * \fBarr\fP"
.br
.ti -1c
.RI "\fBGCStringValue\fP * \fBstring\fP"
.br
.ti -1c
.RI "\fBGCUserdataValue\fP * \fBuserdata\fP"
.br
.ti -1c
.RI "\fBGCFunctionValue\fP * \fBfunc\fP"
.br
.ti -1c
.RI "\fBGCCFunctionValue\fP * \fBcfunc\fP"
.br
.ti -1c
.RI "double \fBnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1370 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
