.TH "ObjectScript::OS::Core::GCValue" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectScript::OS::Core::GCValue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjectScript::OS::Core::GCArrayValue\fP, \fBObjectScript::OS::Core::GCCFunctionValue\fP, \fBObjectScript::OS::Core::GCFunctionValue\fP, \fBObjectScript::OS::Core::GCObjectValue\fP, and \fBObjectScript::OS::Core::GCStringValue\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue_id\fP"
.br
.ti -1c
.RI "int \fBref_count\fP"
.br
.ti -1c
.RI "int \fBexternal_ref_count\fP"
.br
.ti -1c
.RI "\fBGCValue\fP * \fBprototype\fP"
.br
.ti -1c
.RI "\fBGCValue\fP * \fBhash_next\fP"
.br
.ti -1c
.RI "\fBGCValue\fP * \fBhash_next_free_candidate\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBtable\fP"
.br
.ti -1c
.RI "\fBGCStringValue\fP * \fBname\fP"
.br
.ti -1c
.RI "int \fBgc_step_type\fP"
.br
.ti -1c
.RI "OS_EValueType \fBtype\fP"
.br
.ti -1c
.RI "bool \fBis_destructor_called\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1236 of file objectscript\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
