.TH "src/os-std.cpp" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/os-std.cpp \- ObjectScript standart library extension\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IceTea\&.h'\fP
.br
\fC#include 'os\-icetea\&.h'\fP
.br
\fC#include 'os\-stacker\&.h'\fP
.br
\fC#include 'wildcard\&.hpp'\fP
.br
\fC#include 'InternalIceTeaPlugin\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIceTeaSTD\fP"
.br
.ti -1c
.RI "class \fBIceTeaSTDProvider\fP"
.br
.ti -1c
.RI "class \fBIceTeaSTDInternalPlugin\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBwildcard_match\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "int \fBos_exit\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "int \fBos_die\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile class \fBIceTeaSTDInternalPlugin\fP \fBIceTeaSTDPluginInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ObjectScript standart library extension\&. 

This file contains a minimal extension that adds useful methods to objects and arrays and offers functions for general use\&. 
.PP
Definition in file \fBos\-std\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
