.TH "OS_FunctionClassImp0_run< void, T                           >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OS_FunctionClassImp0_run< void, T                           > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void(T::* \fBF\fP) ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBrun\fP (OS *os, int params, int, int, void *user_param)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct OS_FunctionClassImp0_run< void, T                           >"

.PP
Definition at line 771 of file os\-binder\-function\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
