.TH "OSFileCache" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSFileCache \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fB__construct\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fB__set\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fB__get\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fB__del\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fB__isset\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBgetKeys\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBsync\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file os\-cache\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
