.TH "OSSubProcess" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSSubProcess \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fB__construct\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fB__destruct\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBset_env\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBdel_env\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBget_env\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBwrite_stdin\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBclose_stdin\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBclose_stdout\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBclose_stderr\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBstdout\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBstderr\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBerror\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBerror_number\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBerror_text\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBexit_code\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBkill\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBexecute\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.ti -1c
.RI "static int \fBtick\fP (\fBObjectScript::OS\fP *os, int params, int closure_values, int need_ret_values, void *userData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file os\-exec\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
