.TH "pluma::Host" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pluma::Host \- Manages providers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Host\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBadd\fP (\fBProvider\fP *provider)"
.br
.RI "\fIAdd provider\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPluginManager\fP"
.br
.ti -1c
.RI "class \fBProvider\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages providers\&. 
.PP
Definition at line 44 of file Host\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool pluma::Host::add (\fBProvider\fP * provider)"

.PP
Add provider\&. \fBProvider\fP type and version are checked\&. Only known and valid provider types are accepted\&.
.PP
\fBParameters:\fP
.RS 4
\fIprovider\fP \fBProvider\fP to be added\&.
.RE
.PP
\fBReturns:\fP
.RS 4
True if the provider is accepted\&. 
.RE
.PP

.PP
Definition at line 42 of file Host\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
