.TH "pluma::DLibrary" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pluma::DLibrary \- Manages a Dynamic Linking Library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DLibrary\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~DLibrary\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "void * \fBgetSymbol\fP (const std::string &symbol)"
.br
.RI "\fIGet a symbol from the library\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDLibrary\fP * \fBload\fP (const std::string &path)"
.br
.RI "\fILoad a library\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Manages a Dynamic Linking Library\&. 
.PP
Definition at line 49 of file DLibrary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "pluma::DLibrary::~DLibrary ()"

.PP
Destructor\&. Close and free the opened library (if any)\&. 
.PP
Definition at line 67 of file DLibrary\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void * pluma::DLibrary::getSymbol (const std::string & symbol)"

.PP
Get a symbol from the library\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsymbol\fP Symbol that we're looking for\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Pointer to what the symbol refers to, or NULL if the symbol is not found\&. 
.RE
.PP

.PP
Definition at line 79 of file DLibrary\&.cpp\&.
.SS "\fBDLibrary\fP * pluma::DLibrary::load (const std::string & path)\fC [static]\fP"

.PP
Load a library\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to the library\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Pointer to the loaded library, or NULL if failed\&. 
.RE
.PP

.PP
Definition at line 37 of file DLibrary\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
