.TH "ProcessInstance" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcessInstance \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessInstance\fP (\fBSyncProcess\fP *p)"
.br
.ti -1c
.RI "\fBProcessInstance\fP (\fBAsyncProcess\fP *p)"
.br
.ti -1c
.RI "bool \fBisSync\fP ()"
.br
.ti -1c
.RI "\fBSyncProcess\fP * \fBgetSyncProcess\fP ()"
.br
.ti -1c
.RI "\fBAsyncProcess\fP * \fBgetAsyncProcess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file os\-exec\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
