.TH "SI_GenericCase< SI_CHAR >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SI_GenericCase< SI_CHAR > \- Generic case-sensitive less than comparison\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleIni\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const SI_CHAR *pLeft, const SI_CHAR *pRight) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class SI_CHAR>
.br
struct SI_GenericCase< SI_CHAR >"
Generic case-sensitive less than comparison\&. 

This class returns numerically ordered ASCII case-sensitive text for all possible sizes and types of SI_CHAR\&. 
.PP
Definition at line 2685 of file SimpleIni\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
