.TH "stlplus::file_specification" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stlplus::file_specification \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitialise_folder\fP (const std::string &spec)"
.br
.ti -1c
.RI "bool \fBinitialise_file\fP (const std::string &spec)"
.br
.ti -1c
.RI "bool \fBsimplify\fP (void)"
.br
.ti -1c
.RI "bool \fBmake_absolute\fP (const std::string &root=folder_current_full())"
.br
.ti -1c
.RI "bool \fBmake_absolute\fP (const \fBfile_specification\fP &root)"
.br
.ti -1c
.RI "bool \fBmake_relative\fP (const std::string &root=folder_current_full())"
.br
.ti -1c
.RI "bool \fBmake_relative\fP (const \fBfile_specification\fP &root)"
.br
.ti -1c
.RI "bool \fBrelative\fP (void) const "
.br
.ti -1c
.RI "bool \fBabsolute\fP (void) const "
.br
.ti -1c
.RI "void \fBset_relative\fP (void)"
.br
.ti -1c
.RI "void \fBset_absolute\fP (void)"
.br
.ti -1c
.RI "const std::string & \fBdrive\fP (void) const "
.br
.ti -1c
.RI "std::string & \fBdrive\fP (void)"
.br
.ti -1c
.RI "void \fBset_drive\fP (const std::string &drive)"
.br
.ti -1c
.RI "const std::vector< std::string > & \fBpath\fP (void) const "
.br
.ti -1c
.RI "std::vector< std::string > & \fBpath\fP (void)"
.br
.ti -1c
.RI "void \fBset_path\fP (const std::vector< std::string > &path)"
.br
.ti -1c
.RI "void \fBadd_subpath\fP (const std::string &subpath)"
.br
.ti -1c
.RI "unsigned \fBsubpath_size\fP (void) const "
.br
.ti -1c
.RI "const std::string & \fBsubpath_element\fP (unsigned i) const "
.br
.ti -1c
.RI "void \fBsubpath_erase\fP (unsigned i)"
.br
.ti -1c
.RI "const std::string & \fBfile\fP (void) const "
.br
.ti -1c
.RI "std::string & \fBfile\fP (void)"
.br
.ti -1c
.RI "void \fBset_file\fP (const std::string &file)"
.br
.ti -1c
.RI "std::string \fBimage\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file file_system\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
