.TH "stlplus::async_subprocess" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stlplus::async_subprocess \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAsyncProcess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_variable\fP (const std::string &name, const std::string &value)"
.br
.ti -1c
.RI "bool \fBremove_variable\fP (const std::string &name)"
.br
.ti -1c
.RI "const \fBenv_vector\fP & \fBget_variables\fP (void) const "
.br
.ti -1c
.RI "bool \fBspawn\fP (const std::string &path, const \fBarg_vector\fP &argv, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)"
.br
.ti -1c
.RI "bool \fBspawn\fP (const std::string &command_line, bool connect_stdin=false, bool connect_stdout=false, bool connect_stderr=false)"
.br
.ti -1c
.RI "virtual bool \fBcallback\fP (void)"
.br
.ti -1c
.RI "bool \fBtick\fP (void)"
.br
.ti -1c
.RI "bool \fBkill\fP (void)"
.br
.ti -1c
.RI "int \fBwrite_stdin\fP (std::string &buffer)"
.br
.ti -1c
.RI "int \fBread_stdout\fP (std::string &buffer)"
.br
.ti -1c
.RI "int \fBread_stderr\fP (std::string &buffer)"
.br
.ti -1c
.RI "void \fBclose_stdin\fP (void)"
.br
.ti -1c
.RI "void \fBclose_stdout\fP (void)"
.br
.ti -1c
.RI "void \fBclose_stderr\fP (void)"
.br
.ti -1c
.RI "bool \fBerror\fP (void) const "
.br
.ti -1c
.RI "int \fBerror_number\fP (void) const "
.br
.ti -1c
.RI "std::string \fBerror_text\fP (void) const "
.br
.ti -1c
.RI "int \fBexit_status\fP (void) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_error\fP (int)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBm_pid\fP"
.br
.ti -1c
.RI "int \fBm_child_in\fP"
.br
.ti -1c
.RI "int \fBm_child_out\fP"
.br
.ti -1c
.RI "int \fBm_child_err\fP"
.br
.ti -1c
.RI "\fBenv_vector\fP \fBm_env\fP"
.br
.ti -1c
.RI "int \fBm_err\fP"
.br
.ti -1c
.RI "int \fBm_status\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 232 of file subprocesses\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
