.TH "stlplus::arg_vector" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stlplus::arg_vector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBarg_vector\fP (const \fBarg_vector\fP &)"
.br
.ti -1c
.RI "\fBarg_vector\fP (char **)"
.br
.ti -1c
.RI "\fBarg_vector\fP (const std::string &)"
.br
.ti -1c
.RI "\fBarg_vector\fP (const char *)"
.br
.ti -1c
.RI "\fBarg_vector\fP & \fBoperator=\fP (const \fBarg_vector\fP &)"
.br
.ti -1c
.RI "\fBarg_vector\fP & \fBoperator=\fP (char **)"
.br
.ti -1c
.RI "\fBarg_vector\fP & \fBoperator=\fP (const std::string &)"
.br
.ti -1c
.RI "\fBarg_vector\fP & \fBoperator=\fP (const char *)"
.br
.ti -1c
.RI "\fBarg_vector\fP & \fBoperator+=\fP (const std::string &)"
.br
.ti -1c
.RI "\fBarg_vector\fP & \fBoperator\-=\fP (const std::string &)"
.br
.ti -1c
.RI "void \fBinsert\fP (unsigned index, const std::string &)  throw (std::out_of_range)"
.br
.ti -1c
.RI "void \fBclear\fP (unsigned index)  throw (std::out_of_range)"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "unsigned \fBsize\fP (void) const "
.br
.ti -1c
.RI "\fBoperator char **\fP (void) const "
.br
.ti -1c
.RI "char ** \fBargv\fP (void) const "
.br
.ti -1c
.RI "char * \fBoperator[]\fP (unsigned index) const   throw (std::out_of_range)"
.br
.ti -1c
.RI "char * \fBargv0\fP (void) const   throw (std::out_of_range)"
.br
.ti -1c
.RI "std::string \fBimage\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file subprocesses\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
