.TH "stlplus::backtick_subprocess" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stlplus::backtick_subprocess \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstlplus::subprocess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBcallback\fP (void)"
.br
.ti -1c
.RI "bool \fBspawn\fP (const std::string &path, const \fBarg_vector\fP &argv)"
.br
.ti -1c
.RI "bool \fBspawn\fP (const std::string &command_line)"
.br
.ti -1c
.RI "std::vector< std::string > \fBtext\fP (void) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_text\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 214 of file subprocesses\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
