.TH "StringTypeStack" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringTypeStack \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectScript::OS::Vector< EStringType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringTypeStack\fP (\fBOS\fP *a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOS\fP * \fBallocator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1928 of file objectscript\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
