.TH "src/threading.h" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/threading.h \- A Threadpool based on Tinythreads++\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'tinythread\&.h'\fP
.br
\fC#include 'fast_mutex\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorkQueue< T, ST >\fP"
.br
.RI "\fIThe actual thread pool\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBThreadFunction\fP) (void *)"
.br
.RI "\fIThe function to be run across threads\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A Threadpool based on Tinythreads++\&. 


.PP
Definition in file \fBthreading\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
