.TH "tinythread" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinythread \- TinyThread++ API Reference 

.SH "Introduction"
.PP
TinyThread++ is a minimal, portable implementation of basic threading classes for C++\&.
.PP
They closely mimic the functionality and naming of the C++11 standard, and should be easily replaceable with the corresponding std:: variants\&.
.SH "Portability"
.PP
The Win32 variant uses the native Win32 API for implementing the thread classes, while for other systems, the POSIX threads API (pthread) is used\&.
.SH "Classes"
.PP
In order to mimic the threading API of the C++11 standard, subsets of several classes are provided\&. The fundamental classes are: 
.PD 0

.IP "\(bu" 2
\fBtthread::thread\fP 
.IP "\(bu" 2
\fBtthread::mutex\fP 
.IP "\(bu" 2
\fBtthread::recursive_mutex\fP 
.IP "\(bu" 2
\fBtthread::condition_variable\fP 
.IP "\(bu" 2
\fBtthread::lock_guard\fP 
.IP "\(bu" 2
\fBtthread::fast_mutex\fP
.PP
.SH "Miscellaneous"
.PP
The following special keywords are available: \fBthread_local\fP\&.
.PP
For more detailed information (including additional classes), browse the different sections of this documentation\&. A good place to start is: \fBtinythread\&.h\fP\&. 
