.TH "tthread::ratio< N, D >" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tthread::ratio< N, D > \- Minimal implementation of the \fCratio\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinythread\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fB_as_double\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<__intmax_t N, __intmax_t D = 1>
.br
class tthread::ratio< N, D >"
Minimal implementation of the \fCratio\fP class\&. 

This class provides enough functionality to implement some basic \fCchrono\fP classes\&. 
.PP
Definition at line 635 of file tinythread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
