.TH "tthread::_thread_start_info" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tthread::_thread_start_info \- Information to pass to the new thread (what to run)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBmFunction\fP )(void *)"
.br
.RI "\fIPointer to the function to be executed\&. \fP"
.ti -1c
.RI "void * \fBmArg\fP"
.br
.RI "\fIFunction argument for the thread function\&. \fP"
.ti -1c
.RI "\fBthread\fP * \fBmThread\fP"
.br
.RI "\fIPointer to the thread object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information to pass to the new thread (what to run)\&. 
.PP
Definition at line 150 of file tinythread\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
