.TH "tthread::thread::id" 3 "Sat Mar 26 2016" "IceTea" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tthread::thread::id \- Thread ID\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinythread\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBid\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBid\fP (unsigned long int aId)"
.br
.ti -1c
.RI "\fBid\fP (const \fBid\fP &aId)"
.br
.ti -1c
.RI "\fBid\fP & \fBoperator=\fP (const \fBid\fP &aId)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBid\fP &aId1, const \fBid\fP &aId2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBid\fP &aId1, const \fBid\fP &aId2)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBid\fP &aId1, const \fBid\fP &aId2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBid\fP &aId1, const \fBid\fP &aId2)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBid\fP &aId1, const \fBid\fP &aId2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBid\fP &aId1, const \fBid\fP &aId2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBid\fP &obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Thread ID\&. 

The thread ID is a unique identifier for each thread\&. 
.PP
\fBSee also:\fP
.RS 4
\fBthread::get_id()\fP 
.RE
.PP

.PP
Definition at line 572 of file tinythread\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tthread::thread::id::id ()\fC [inline]\fP"

.PP
Default constructor\&. The default constructed ID is that of thread without a thread of execution\&. 
.PP
Definition at line 577 of file tinythread\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IceTea from the source code\&.
